#!/bin/bash

showDateAndTime() {
	date +'%R, %a %d %b'
}

delim='    '

while :; do
	xsetroot -name "$(showDateAndTime);$(showWifi)$delim$(showVolume)$delim$(showMem)$delim$(showBattery)"
	sleep	1
done
