#!/bin/bash

showDateAndTime() {
	date +'%R, %a %b %d'
}

delim='    '

while :; do
	xsetroot -name "$(showDateAndTime);$(showWifi)$delim$(showVolume)$delim$(showMem)$delim$(showBattery)"
	sleep	1
done
